name: 'Send Mail'
description: 'sending email.'
inputs:
  env:  # id of input
    description: 'env'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Publish grant tasks package
      run: |
          chmod +x ${{ github.action_path }}/publishgranttaskspackage.sh ${{ inputs.env }}
          ${{ github.action_path }}/publishgranttaskspackage.sh
      shell: bash      
