name: 'Prisma Scan'
description: 'scanning cloudformation templates.'
runs:
  using: "composite"
  steps:
   - name: Checkout the commit
     uses: actions/checkout@v2
   - name: Run shell Script
     run: |
         chmod +x ${{ github.action_path }}/prisma.sh
         ${{ github.action_path }}/prisma.sh       
     shell: bash
